### ISSUE TITLE
Unable to install on PHP 5.5

### ISSUE THREAD

**Issue by aruku** [trappar/AliceGenerator#5]
By mistake, I installed alice-generator-bundle, and that worked like a charm, but after realizing that I need only the library and not the bundle, Composer doesn't allow me to install it:

```
  [InvalidArgumentException]                                                                       
  Could not find package trappar/alice-generator at any version matching your PHP version 5.5.0.0  
```

I don't know what is happening, because the PHP requirement for both packages is the same.

**Comment by trappar** [comment]
I'm not actually sure why you would have been able to install either. Both [AliceGenerator](https://github.com/trappar/AliceGenerator/blob/master/composer.json#L14) and [AliceGeneratorBundle](https://github.com/trappar/AliceGeneratorBundle/blob/master/composer.json#L14) require PHP 5.6.

You may be able to get away with running:

``` bash
composer install --ignore-platform-reqs
```

However, the version requirement is there for a reason. I can't recall exactly what breaks on 5.5, but when I was getting Travis setup I widened the allowed versions as much as would pass in testing, and apparently 5.5 did not pass. Feel free to give it a try though. You could always submit a PR adding 5.5 or lower compatibility if you really wanted.

**Comment by aruku** [comment]
Wow, that shows how "much" attention I was putting into the process...
Anyway, that parameter didn't help. I'll keep trying.
