### ISSUE TITLE
Provide doctrine bridge

### ISSUE THREAD

**Issue by theofidry** [trappar/AliceGenerator#8]
Maybe this is out of scope of this library but one thing that would be interesting is to be able to, from Doctrine ORM and its configuration, get the content of all the tables (the database, tables discovery and transformation into objects can be done via Doctrine) and generate fixture files from it.

So in other words, providing an out of the box support command generating all the fixture files from the database.

**Comment by trappar** [comment]
If I'm understanding correctly then this is actually [already a feature of AliceGeneratorBundle](https://github.com/trappar/AliceGeneratorBundle#usage). I suppose I could have written it into this library so it would be framework agnostic, it just would have been a bit more work, and would have made this library depend on the Symfony console component.

**Comment by theofidry** [comment]
I'll have to give it a try then ;)
