### ISSUE TITLE
Customizing Reference Naming Strategy without numbers

### ISSUE THREAD

**Issue by poteirard** [trappar/AliceGenerator#9]
Hi,

First of all thank you for this repo, it's helping me a lot in my project.

However one thing I miss (or at least I didn't find how to do it) is to be able to generate a name with the ReferenceNamer without the number at the end of the name "-1".

For example to have a reference name like "NormalUser" not "NormalUser1".

Thank you !

**Comment by trappar** [comment]
That's not possible at the moment. The numbering and final assembly of the reference names takes place inside ValueVisitor. Shouldn't be very difficult to move the numbering responsibility into the ReferenceNamer though, which would make it possible to create a ReferenceNamer which does what you want. I'm currently on vacation but I'll look into that when I get back. Alternatively if you would like to try adding that functionality yourself feel free to open a pull request.

Glad you're finding the repo useful!

**Comment by rcwsr** [comment]
@trappar, @poteirard , did you get any where with this?

**Comment by trappar** [comment]
Never ended up circling back to it. I'm pretty busy with other projects right now. Feel free to work on it if you want. I always welcome pull requests.

**Comment by poteirard** [comment]
Sorry I'm busy too u__u

**Comment by rcwsr** [comment]
Ok I'll have a go at it if I can find the time too!

**Comment by trappar** [comment]
I'm working on updating the tests to get everything passing again. That should probably help you get started :)

**Comment by pscheit** [comment]
@trappar @rcwsr did someone start? ;)

**Comment by rcwsr** [comment]
I didn't have time I'm afraid

**Comment by pscheit** [comment]
it's hard to keep backwards compatibility here.. The actual change in ValueVisitor not very complicated. 

1)
```
interface ReferenceNamer::getUniqueReference($object, $numericKey)
```
and call it in visitObject() from value Visitor

But this would change the ReferenceNamer interface.

2)
```
interface UniqueReferenceNamer extends ReferenceNamer
  function getUniqueReference()
```

and then checking for the subinterface with `instanceof UniqueReferenceNamer` in the ValueVisitor. But I dont like that.

3)
add `fixtureGenerationContext::getUniqueReferenceNamer()` and make it implement the default for now (referenceNamer prefix + id). But this would introduce another referenceNamer like the previous one.

I think the cleanest is, to break backwards compatibility. I'll send a PR for that.
